### ISSUE TITLE
Thanks your work! This node has not input, I can not deal with some input prompt, Wise it's improve.

### ISSUE THREAD

**Issue by jimmylearner** [smthemex/ComfyUI_ChatGLM_API#1]

**Comment by smthemex** [comment]
Because this node is connected to LLM servers like CHATGPT, I prefer that you use natural language directly in the input of the prompt to describe what content you need, such as what content, how many words, how many detailed words, etc., rather than tuning parameters in the node.
In addition, due to the laws of the Chinese government, all NSFW content will be filtered out on the server. We do not advocate the use of pornographic or violent elements, especially in the field of AIGC
I'm not sure if this answer will help you, because this node has only been established in less than 2 days, and many contents need to be gradually optimized.
Thank you for your feedback
